---
- name: Set Broker Id
  set_fact: broker_id={{item.0 + 1}}
  with_indexed_items: "{{ groups['kafka-server-nodes'] }}"
  when: item.1 == "{{inventory_hostname}}"
 
- name: Template kafka server properties 
  template:
    src: server.properties
    dest: /etc/kafka/

- debug: var=ansible_facts
