---
- include_vars: group_vars/kafka-server-nodes

- name: Set Broker Id
  set_fact: broker_id={{item.0 + 1}}
  with_indexed_items: "{{ groups['kafka-server-nodes'] }}"
  when: item.1 == "{{inventory_hostname}}"

- name: setup kafka dir
  file:
    path: /var/lib/kafka
    owner: cp-kafka
    group: confluent
    mode: 640
    state: directory

- name: setup kafka streams dir
  file:
    path: /var/lib/kafka-streams
    owner: cp-ksql
    group: confluent
    mode: 640
    state: directory

- name: Template kafka server properties 
  template:
    src: server.properties
    dest: /etc/kafka/

- name: Template kafka consumer properties
  template:
    src: consumer.properties
    dest: /etc/kafka/

- name: Template kafka-rest.properties
  template:
    src: kafka-rest.properties
    dest: /etc/kafka/

#- name: Template ksql-server.properties
#  template:
#    src: ksql-server.properties
#    dest: /etc/kafka/

- name: Template producer.properties
  template:
    src: producer.properties
    dest: /etc/kafka/

- name: Template zookeeper.properties
  template:
    src: zookeeper.properties
    dest: /etc/kafka/

- name: start kafka server
  systemd:
    name: confluent-kafka
    state: started

- name: start kafka rest
  systemd:
    name: confluent-kafka-rest
    state: started

- name: start ksql server
  systemd:
    name: confluent-ksql
    state: started

- name: start schema registry
  systemd:
    name: confluent-schema-registry
    state: started

- name: start connect service
  systemd:
    name: confluent-kafka-connect
    state: started

- debug: var=ansible_facts
