---
- include_vars: group_vars/kafka-server-nodes

- name: Include partitioning.yml
  include: partitioning.yml
  with_flattened:
    - "{{ kafka_disk|default([]) }}"

- name: Mount kafka disk under /kafka
  mount: state=mounted
         src="/dev/{{ kafka_disk }}1"
         name="/kafka"
         fstype="{{ data_disks_filesystem }}"
         opts=defaults,noatime
         dump=0
         passno=0
  when: kafka_disk is defined and kafka_disk and ansible_devices[kafka_disk] is defined

- name: Set Broker Id
  set_fact: broker_id={{item.0 + 1}}
  with_indexed_items: "{{ groups['kafka-server-nodes'] }}"
  when: item.1 == "{{inventory_hostname}}"
 
- name: Template kafka server properties 
  template:
    src: server.properties
    dest: /etc/kafka/

- name: Template kafka consumer properties
  template:
    src: consumer.properties
    dest: /etc/kafka/

- name: Template kafka-rest.properties
  template:
    src: kafka-rest.properties
    dest: /etc/kafka/

#- name: Template ksql-server.properties
#  template:
#    src: ksql-server.properties
#    dest: /etc/kafka/

- name: Template producer.properties
  template:
    src: producer.properties
    dest: /etc/kafka/

- name: Template zookeeper.properties
  template:
    src: zookeeper.properties
    dest: /etc/kafka/

- debug: var=ansible_facts
