---

- name: add prometheus system user
  user:
    name: prometheus
    system: yes

- name: setup prometheus dir
  file:
    path: "{{ prometheus_dir }}"
    state: directory

- name: download prometheus
  get_url:
    url: "{{ prometheus_url }}/{{ prometheus_file }}"
    dest: "{{ tmp_dir }}/"

- name: download prometheus jmx exporter
  get_url:
    url: "{{ prometheus_jmx_url }}"
    dest: "{{ prometheus_dir }}/"

- name: download kafka prometheus yaml
  get_url:
    url: "{{ prometheus_kafka_yaml }}"
    dest: "{{ prometheus_dir }}/"

- name: chown prometheus dirs
  file: 
    dest: "{{ prometheus_dir }}"
    owner: prometheus
    group: prometheus 
    recurse: yes

- name: update kafka service 
  copy:
    src: "confluent-kafka.service"
    dest: "/usr/lib/systemd/system/"

- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart kafka service
  systemd:
    name: confluent-kafka
    state: started

