---
- name: Set iptables between cluster nodes
  lineinfile: dest=/etc/sysconfig/iptables
              insertbefore="^-A INPUT"
              line="-A INPUT -s {{ hostvars[item][['ansible_', hostvars[item]['cluster_interface']]|join]['ipv4']['address'] }}/32 -j ACCEPT"
              state=present
  with_items: play_hosts
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"
  notify: Restart iptables

- name: Set iptables to allow cluster access from external IPs
  lineinfile: dest=/etc/sysconfig/iptables
              insertbefore="^-A INPUT"
              line="-A INPUT -s {{ item }}/32 -j ACCEPT"
              state=present
  with_items: cloud_config.allowed_external_ips
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"
  notify: Restart iptables

- name: setup firewalld public allows
  command: firewall-cmd --permanent --zone=public --add-rich-rule='rule family="ipv4" source address="{{ hostvars[item][['ansible_', hostvars[item]['cluster_interface']]|join]['ipv4']['address'] }}" accept'
  with_items: play_hosts
  notify: reload firewalld
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

- name: Set UFW rules between cluster nodes
  ufw: rule=allow src={{ hostvars[item][['ansible_', hostvars[item]['cluster_interface']]|join]['ipv4']['address'] }}
  with_items: play_hosts
  when: ansible_distribution == "Ubuntu"

- name: Set UFW to allow cluster access from external IPs
  ufw: rule=allow src={{ item }}
  with_items: cloud_config.allowed_external_ips
  when: ansible_distribution == "Ubuntu"
