---
- name: "Install epel"
  yum: name=http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm state=present

- name: Ensure required packages are installed
  yum: name={{ item }} state=present
  with_items:
    - python-simplejson
    - python-httplib2
    - man
    - man-pages
    - vim-enhanced
    - sysstat
    - lsof
    - jwhois
    - telnet
    - nc
    - libselinux-python
    - ntp
    - parted
    - mc
    - perl
    - openssh-clients
    - util-linux-ng
    - vim-enhanced
    - iotop
    - links
    - unzip
    - curl
    - wget

- name: Disable yum excludes
  lineinfile: dest=/etc/yum.conf backrefs=yes regexp='^exclude=(.*)$' line='#exclude=\1'

- name: Update all packages
  yum: name=* state=latest

- name: Make sure ntpd is stopped
  service: name=ntpd state=stopped

- name: Start ntpdate
  service: name=ntpdate state=started

- name: Start ntpd
  service: name=ntpd state=started enabled=yes

- name: Stop unneeded services
  service: name={{ item }} state=stopped enabled=no
  with_items:
    - mysqld
    - httpd
  ignore_errors: true

- name: Disable MySQL skip-name-resolve if present
  lineinfile: dest=/etc/my.cnf
              regexp="^skip[-_]name[-_]resolve"
              state=absent

- name: Set nofile limits
  lineinfile: dest=/etc/security/limits.conf
              insertbefore="^# End of file"
              state=present
              line="{{ item }}"
  with_items:
    - "* soft nofile 32768"
    - "* hard nofile 32768"

- name: Set nproc limits
  lineinfile: dest=/etc/security/limits.d/90-nproc.conf
              insertafter=EOF
              state=present
              line="{{ item }}"
              mode=0644
  with_items:
    - "* soft nproc 32768"
    - "* hard nproc 32768"

- name: Load bridge kernel module to prevent sysctl errors
  modprobe: name=bridge state=present

- name: Set swappiness to 1
  sysctl: name=vm.swappiness value=1 state=present

- name: Disable IPv6
  sysctl: name=net.ipv6.conf.all.disable_ipv6 value=1 state=present

- name: Disable IPv6
  sysctl: name=net.ipv6.conf.default.disable_ipv6 value=1 state=present

- name: Get number of kernels in grub.conf
  shell: grep -E "^[[:blank:]]*kernel" /boot/grub/grub.conf | grep -v transparent_hugepage
  register: grep_result
  ignore_errors: true

- name: Disable Transparent Huge Pages
  lineinfile: dest=/boot/grub/grub.conf
              backrefs=True
              state=present
              regexp='(^\s*kernel(\s+(?!transparent_hugepage=never)[\w=/\-\.\,]+)*)\s*$'
              line='\1 transparent_hugepage=never'
  register: result
  with_items: grep_result.stdout_lines

- name: Disable Transparent Huge Pages until reboot
  shell: echo never > /sys/kernel/mm/transparent_hugepage/enabled && echo never > /sys/kernel/mm/transparent_hugepage/defrag
  ignore_errors: true

- name: Reconfigure resolv.conf domain
  lineinfile: dest=/etc/resolv.conf regexp='^domain\s+(?! {{ ansible_domain }} ).*$' line='domain {{ ansible_domain }}'
  when: ansible_domain != ""

- name: Reconfigure resolv.conf search
  lineinfile: dest=/etc/resolv.conf regexp='^search\s+(?! {{ ansible_domain }} ).*$' line='search {{ ansible_domain }}'
  when: ansible_domain != ""

- name: Configure bonding
  include: bonding.yml
  when: bond_interfaces is defined

- name: Set hosts file
  template: src=hosts.j2 dest=/etc/hosts mode=0644

- include: iptables.yml
  when: cloud_nodes_count is defined and cloud_nodes_count > 0

- include: partitioning.yml
