---
- name: Install the Ambari server
  yum: name=ambari-server state=present

- name: Run Ambari Server setup
  shell: /usr/sbin/ambari-server setup -s

- name: Enable the ambari-server service
  service: name=ambari-server state=restarted enabled=yes

- name: Pausing to allow the ambari-agents to register
  pause: seconds=60
