---
- name: Restart iptables
  service: name=iptables state=restarted enabled=yes

- name: Restart network interfaces
  shell: ifdown {{ item }}; ifup {{ item }}; ifup {{ cluster_interface }}
  with_flattened:
    - cluster_interface
    - bond_interfaces
  notify: Gather facts

- name: Gather facts
  action: setup

- name: Run depmod
  command: depmod
