package_info:
  pkg_mgr: yum
  args:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  pkgs:
    - cloudera-manager-daemons
    - cloudera-manager-agent

resolv_conf: "/etc/resolv.conf"

cloudera_repo_file: "/etc/yum.repos.d/cloudera.repo"

java_jce_url: "http://23.253.245.225/jdk-files/" 
java_jce_zip: "jce_policy-8.zip"
unarchived_directory: "UnlimitedJCEPolicyJDK8"
java_jdk_url: "http://23.253.245.225/jdk-files/"
java_jdk_rpm: "jdk-8u241-linux-x64.rpm"

tmp_dir: "/tmp/"

java_jce_remote_src: "yes"

java_jdk_remote_src: "yes"

java_home: "/usr/java/jdk1.8.0_241-amd64/"
