---

- name: setup prometheus dir
  file:
    path: "{{ prometheus_dir }}"
    state: directory

- name: download prometheus
  get_url:
    url: "{{ prometheus_url }}/{{ prometheus_file }}"
    dest: "{{ tmp_dir }}/"

- name: Extract prometheus.tgz into prometheus dir
  unarchive:
    src: "{{ tmp_dir }}/{{ prometheus_file }}"
    dest: "{{ prometheus_dir }}/"
    remote_src: yes

- name: install prometheus config
  template:
    src: "prometheus.yml"
    dest: "{{ prometheus_dir }}/"

- name: install alerts config
  template:
    src: "kafka.alert.rules.yml
    dest: "{{ prometheus_dir }}/"

- name: Cleanup tmp files
  file:
    path: "{{ tmp_dir }}/{{ prometheus_file }}"
    state: absent

- name: setup prometheus user
  user:
    name: prometheus
    shell: /sbin/nologin
    home: "{{ prometheus_dir }}"
  ignore_errors: yes

- name: chown prometheus dirs
  file: 
    dest: "{{ prometheus_dir }}"
    owner: prometheus
    group: prometheus 
    recurse: yes

- name: add prometheus service
  copy:
    src: prometheus.service
    dest: /usr/lib/systemd/system/prometheus.service

- name: reload systemd
  systemd:
    daemon_reload: yes

- name: start prometheus service
  systemd:
    name: prometheus
    state: started
