---
- name: Load OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family|lower }}.yml"
        - defaults.yml
      paths:
        - ../vars

- name: Ensure required packages are installed (yum)
  yum:
    name: "{{ item }}"
    update_cache: yes
    state: installed
  with_items: "{{ pkgs }}"
  when: ansible_os_family == "RedHat"

- include_vars: mysql_vars.yml

- name: mysql config template
  template: src=my.cnf dest=/etc/

- name: start mysql
  service: name=mariadb state=started enabled=yes

- name: copy db dump to server
  copy: src={{ item }}.sql dest=/tmp
  with_items: "{{ db_names }}"

- name: create DB references
  mysql_db: name={{ item }} state=present
  with_items: "{{ db_names }}"

- name: import DBs
  mysql_db: name={{ item }} state=import target=/tmp/{{ item }}.sql
  with_items: "{{ db_names }}"

- name: setup Activity Monitor DB user
  mysql_user: name=amon password={{ amon_pass }} host="{{ hostvars[item]['ansible_'~hostvars[item].cluster_interface|default(hostvars[item].ansible_default_ipv4.alias)]['ipv4']['address'] }}" priv=amon.*:ALL state=present
  with_items: "{{ play_hosts }}"
 
- name: setup Report Manager DB user
  mysql_user: name=rman password={{ rman_pass }} host="{{ hostvars[item]['ansible_'~hostvars[item].cluster_interface|default(hostvars[item].ansible_default_ipv4.alias)]['ipv4']['address'] }}" priv=rman.*:ALL state=present
  with_items: "{{ play_hosts }}"

- name: setup Sentry DB user
  mysql_user: name=sentry password={{ sentry_pass }} host="{{ hostvars[item]['ansible_'~hostvars[item].cluster_interface|default(hostvars[item].ansible_default_ipv4.alias)]['ipv4']['address'] }}" priv=sentry.*:ALL state=present
  with_items: "{{ play_hosts }}"

- name: setup Cloudera Navigator DB user
  mysql_user: name=nav password={{ nav_pass }} host="{{ hostvars[item]['ansible_'~hostvars[item].cluster_interface|default(hostvars[item].ansible_default_ipv4.alias)]['ipv4']['address'] }}" priv=nav.*:ALL state=present
  with_items: "{{ play_hosts }}"

- name: setup Cloudera Navigator Metadata DB user
  mysql_user: name=navms password={{ navms_pass }} host="{{ hostvars[item]['ansible_'~hostvars[item].cluster_interface|default(hostvars[item].ansible_default_ipv4.alias)]['ipv4']['address'] }}" priv=navms.*:ALL state=present
  with_items: "{{ play_hosts }}"

- name: setup Hive DB user
  mysql_user: name=metastore password={{ hive_pass }} host="{{ hostvars[item]['ansible_'~hostvars[item].cluster_interface|default(hostvars[item].ansible_default_ipv4.alias)]['ipv4']['address'] }}" priv=hive.*:ALL state=present
  with_items: "{{ play_hosts }}"

- name: setup SCM DB user
  mysql_user: name=scm password={{ scm_pass }} host="{{ hostvars[item]['ansible_'~hostvars[item].cluster_interface|default(hostvars[item].ansible_default_ipv4.alias)]['ipv4']['address'] }}" priv=scm.*:ALL state=present
  with_items: "{{ play_hosts }}"
