- name: Install Gems Dependencies for Custom Checks
  gem: name={{ item }} state=latest executable=/opt/sensu/embedded/bin/gem user_install=no
  with_items:
    - rest-client
    - json
  tags:
    - all-servers

- name: Copy Gems to local disk
  copy:
    src=custom_gems/{{ item }}
    dest=/tmp/{{ item }}
    owner=sensu
    group=sensu
    mode=0640
  with_items:
    - sensu-plugins-ambari-0.1.0.gem

- name: Install Custom Gems
  gem: name={{ item }} state=present executable=/opt/sensu/embedded/bin/gem gem_source=/tmp/{{ item }} user_install=no
  with_items:
    - sensu-plugins-ambari-0.1.0.gem

- name: generate ambari plugin json
  template:
    src=check-alerts.json.j2
    dest=/etc/sensu/conf.d/check-alerts.json
    owner=sensu
    group=sensu
    mode=0640
    backup=yes
  notify:
    - restart sensu client
