---
- include_vars: group_vars/kafka-zookeeper-nodes

- name: Set Zookeeper Id
  set_fact: zk_id={{item.0 + 1}}
  with_indexed_items: "{{ groups['kafka-zk-nodes'] }}"
  when: item.1 == "{{inventory_hostname}}"
 
- name: setup zookeeper dir
  file:
    path: /var/lib/zookeeper
    owner: cp-kafka
    group: confluent
    mode: '750'
    state: directory

- name: Template zk id 
  template:
    src: myid.j2
    dest: /var/lib/zookeeper/myid

- name: Template zookeeper.properties
  template:
    src: zookeeper.properties
    dest: /etc/kafka/

- name: start zookeeper
  systemd:
    name: confluent-zookeeper
    state: started 

- debug: var=ansible_facts
