---
- include_vars: group_vars/kafka-zookeeper-nodes

- name: Include partitioning.yml
  include: partitioning.yml
  with_flattened:
    - "{{ zookeeper_disk|default([]) }}"

- name: Mount zookeeper disk under /zookeeper
  mount: state=mounted
         src="/dev/{{ zookeeper_disk }}1"
         name="/zookeeper"
         fstype="{{ data_disks_filesystem }}"
         opts=defaults,noatime
         dump=0
         passno=0
  when: zookeeper_disk is defined and zookeeper_disk and ansible_devices[zookeeper_disk] is defined

- name: Set Zookeeper Id
  set_fact: zk_id={{item.0 + 1}}
  with_indexed_items: "{{ groups['kafka-zk-nodes'] }}"
  when: item.1 == "{{inventory_hostname}}"
 
- name: create postgres dir
  file:
    path: /zookeeper
    owner: cp-kafka

- name: Template zk id 
  template:
    src: myid.j2
    dest: /zookeeper/myid

- name: Template kafka consumer properties
  template:
    src: consumer.properties
    dest: /etc/kafka/

- name: Template kafka-rest.properties
  template:
    src: kafka-rest.properties
    dest: /etc/kafka/

#- name: Template ksql-server.properties
#  template:
#    src: ksql-server.properties
#    dest: /etc/kafka/

- name: Template producer.properties
  template:
    src: producer.properties
    dest: /etc/kafka/

- name: Template zookeeper.properties
  template:
    src: zookeeper.properties
    dest: /etc/kafka/

- debug: var=ansible_facts
