---
- include_vars: mysql_vars.yml

- name: mysql config template
  template: src=my.cnf dest=/etc/

- name: start mysql
  service: name=mariadb state=started enabled=yes

- name: copy db dump to server
  copy: src={{ item }}.sql dest=/tmp
  with_items: "{{ db_names }}"

- name: create DB references
  mysql_db: name={{ item }} state=present
  with_items: "{{ db_names }}"

- name: import DBs
  mysql_db: name={{ item }}state=import target=/tmp/{{ item }}.sql
  with_items: "{{ db_names }}"

- name: setup Activity Monitor DB user
  mysql_user: name=amon password={{ amon_pass }} host_all=yes priv=amon.*:ALL state=present
 
- name: setup Report Manager DB user
  mysql_user: name=rman password={{ rman_pass }} host_all=yes priv=rman.*:ALL state=present

- name: setup Sentry DB user
  mysql_user: name=sentry password={{ sentry_pass }} host_all=yes priv=sentry.*:ALL state=present

- name: setup Cloudera Navigator DB user
  mysql_user: name=nav password={{ nav_pass }} host_all=yes priv=nav.*:ALL state=present

- name: setup Cloudera Navigator Metadata DB user
  mysql_user: name=navms password={{ navms_pass }} host_all=yes priv=navms.*:ALL state=present

- name: setup Hive DB user
  mysql_user: name=metastore password={{ hive_pass }} host_all=yes priv=hive.*:ALL state=present

- name: setup SCM DB user
  mysql_user: name=scm password={{ scm_pass }} host_all=yes priv=scm.*:ALL state=present
