---
- name: Load OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family|lower }}.yml"
        - defaults.yml
      paths:
        - ../vars

- include_vars: group_vars/cloudera

- include_vars: group_vars/postgres_vars.yml

- name: Ensure required packages are installed (yum)
  yum:
    name: "{{ item }}"
    update_cache: yes
    state: installed
  with_items: "{{ pkgs }}"
  when: ansible_os_family == "RedHat"

- include: unbound-dns.yml
  when: use_dns

#- name: setup SCM DB
#  command: /opt/cloudera/cm/schema/scm_prepare_database.sh postgresql -h {{ groups['cm_node'][0] }} scm scm {{ scm_pass }}

- name: download cdh parcel
  get_url:
    url: "{{ parcel_repo_url }}{{ cdh_parcel }}"
    dest: /opt/cloudera/parcel-repo/ 
    owner: cloudera-scm
    group: cloudera-scm

- name: download cdh parcel sha
  get_url:
    url: "{{ parcel_repo_url }}{{ cdh_parcel_sha }}"
    dest: /opt/cloudera/parcel-repo/ 
    owner: cloudera-scm
    group: cloudera-scm

- name: Upload db properties template
  template: src=db.properties dest=/etc/cloudera-scm-server/

- name: Upload db properties template
  template: src=db.mgmt.properties dest=/etc/cloudera-scm-server/

- name: Enable the cloudera manager server service
  service: name=cloudera-scm-server state=started enabled=yes

- name: Waiting for mngr-server to start listening on port 7180
  wait_for: host={{ ansible_nodename }} port=7180

