---
- include: create_groups.yml

- name: "Apply the ambari-agent role to all nodes"
  hosts: hadoop-cluster
  any_errors_fatal: true
  become: yes
  pre_tasks:
    - name: "Show hadoop-cluster info"
      debug: var="{{ hostvars[inventory_hostname] }}"
      when: debug
  roles:
    - cloudera-agent

- name: "setup mysql on master nodes"
  hosts: master-nodes
  any_errors_fatal: true
  become: yes
  pre_tasks:
    - name: "Show cluster info"
      debug: var="{{ hostvars[inventory_hostname] }}"
      when: debug
  roles:
    - cloudera-mysql

- name: "Apply the cloudera-mngr role to cm-node group"
  hosts: cm-node
  become: yes
  pre_tasks:
    - name: "Show cluster info"
      debug: var="{{ hostvars[inventory_hostname] }}"
      when: debug
  roles:
    - cloudera-mngr

- name: Build a Cloudera cluster
  gather_facts: True
  hosts: cm-node
  pre_tasks:
    - name: Install python-pip (yum)
      yum: name='python-pip' state=installed
      when: ansible_os_family == "RedHat"

    - name: Install python-pip (apt)
      apt: name='python-pip' state=installed
      when: ansible_os_family == "Debian"

    - name: Install cm_api
      pip: name='cm_api' state=latest

  tasks:
    - name: Cloudera cluster create request
      action:
        module: cloudera_init
        name: "{{ cluster_name }}"
        fullVersion: 5.6.0
        admin_password: admin
        cm_host: "{{ groups['cm-node'][0] }}"
        hosts: "{{ groups['hadoop-cluster']|join(',') }}"
        state: present
        trial: true
        hive_metastore_host: "{{ groups['cm-node'][0] }}"
        reports_manager_host: "{{ groups['cm-node'][0] }}"

      register: my_cluster
