---

- include: create_groups.yml

- name: "Apply the ambari-agent role to all nodes"
  hosts: hadoop-cluster
  any_errors_fatal: true
  become: yes
  pre_tasks:
    - name: "Show hadoop-cluster info"
      debug: var="{{ hostvars[inventory_hostname] }}"
      when: debug
  roles:
    - cloudera-agent

- name: "Apply the ambari-server role to ambari-node group"
  hosts: cm-node
  become: yes
  roles:
    - cloudera-mngr
