---
- include: create_groups.yml

- name: "Apply the ambari-agent role to all nodes"
  hosts: hadoop-cluster
  any_errors_fatal: true
  become: yes
  pre_tasks:
    - name: "Show hadoop-cluster info"
      debug: var="{{ hostvars[inventory_hostname] }}"
      when: debug
  roles:
    - cloudera-agent

- name: "setup mysql on master nodes"
  hosts: master-nodes
  any_errors_fatal: true
  become: yes
  pre_tasks:
    - name: "Show cluster info"
      debug: var="{{ hostvars[inventory_hostname] }}"
      when: debug
  roles:
    - cloudera-mysql

- name: "Apply the cloudera-mngr role to cm-node group"
  hosts: cm-node
  become: yes
  pre_tasks:
    - name: "Show cluster info"
      debug: var="{{ hostvars[inventory_hostname] }}"
      when: debug
  roles:
    - cloudera-mngr

- name: Build a Cloudera cluster
  gather_facts: True
  hosts: cm-node
  pre_tasks:
    - name: Install python-pip (yum)
      yum: name='python-pip' state=installed
      when: ansible_os_family == "RedHat"

    - name: Install python-pip (apt)
      apt: name='python-pip' state=installed
      when: ansible_os_family == "Debian"

    - name: Install cm_api
      pip: name='cm_api' state=latest

    - name: Copy cluster template
      template: src=library/cloudera/cluster.yamlj2 dest=/opt/
    
    - include_vars: roles/cloudera-mysql/vars/mysql_vars.yml   

    - include_vars: group_vars/cloudera

  tasks:
    - name: Cloudera cluster create request
      action:
        module: cdh.py
        trial: true
      register: my_cdh      

