---
- include: create_kafka_groups.yml

- name: Apply the common role to all nodes
  hosts: kafka-cluster 
  any_errors_fatal: true
  become: yes
  pre_tasks:
    - name: Show kafka-cluster info
      debug: var=hostvars[inventory_hostname]
      when: debug

    - name: include confluent community vars
      include_vars: group_vars/confluent-community

  roles:
    - confluent-community-common

- name: Apply the zookeeper role to all zk  nodes
  hosts: kafka-zookeeper-cluster 
  any_errors_fatal: true
  become: yes
  pre_tasks:
    - name: Show kafka-zookeeper-cluster info
      debug: var=hostvars[inventory_hostname]
      when: debug

    - name: include confluent-community vars
      include_vars: group_vars/confluent-community

  roles:
    - confluent-community-zookeeper

- name: Apply the broker role to all broker nodes
  hosts: kafka-broker-cluster
  any_errors_fatal: true
  become: yes
  pre_tasks:
    - name: Show hadoop-broker-cluster info
      debug: var=hostvars[inventory_hostname]
      when: debug

    - name: include confluent community vars
      include_vars: group_vars/confluent-community
  roles:
    - confluent-community-broker

#- name: "generate site facts"
#  hosts: localhost
#  any_errors_fatal: true
#  become: no
#     dnmemory: "{{ hostvars[groups['slave-nodes'][0]]['ansible_memtotal_mb'] / 1024 }}"
#     mnmemory: "{{ hostvars[groups['master-nodes'][0]]['ansible_memtotal_mb'] / 1024 }}"
#     cores: "{{ hostvars[groups['slave-nodes'][0]]['ansible_processor_count'] }}"
#  tasks:
#    - name: "gather site facts"
#      action:
#        module: confluentsitefacts.py
#          dnmemory="{{ dnmemory }}"
#          mnmemory="{{ mnmemory }}"
#          cores="{{ cores }}"
#          manager_server="localhost"
#          ambari_pass="admin"
#          cluster_name="{{ cluster_name }}"
#          compare="false"
#          current_facts="false"
#
- name: Apply the confluent-community manager  role to manager node group
  hosts: kafka-manager
  become: yes
  pre_tasks:
    - name: include confluent community vars
      include_vars: group_vars/confluent-community
  roles:
    - confluent-community-mngr
