---
- name: Add nodes to required groups
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Add all cluster nodes to the hadoop-cluster group
      check_mode: no
      add_host:
        name: "{{ hostvars[item].inventory_hostname }}"
        ansible_host: "{{ hostvars[item].ansible_host|default(hostvars[item].ansible_ssh_host) }}"
        ansible_user: "{{ hostvars[item].ansible_user|default('root') }}"
        ansible_ssh_pass: "{{ hostvars[item].ansible_ssh_pass|default('') }}"
        ansible_become_user: root
        ansible_become_pass: "{{ hostvars[item].ansible_ssh_pass|default('') }}"
        groups: hadoop-cluster
      with_flattened:
        - "{{ groups['master-nodes']|default([]) }}"
        - "{{ groups['slave-nodes']|default([]) }}"
        - "{{ groups['edge-nodes']|default([]) }}"
      register: hadoop-cluster    
      when: "'hadoop-cluster' not in groups or groups['hadoop-cluster']|length < 1"

    - name: debugging some vars
      debug:
        var: groups['hadoop-cluster']

    - name: "include cdh vars"
      include_vars: group_vars/cloudera
      when: distro == "cdh"

    - name: "include hdp vars"
      include_vars: group_vars/hortonworks
      when: distro == "hdp"

    - name: Add the last masternode to ambari-node variable group
      check_mode: no
      add_host:
        name: "{{ hostvars[item].inventory_hostname }}"
        ansible_host: "{{ hostvars[item].ansible_host|default(hostvars[item].ansible_ssh_host) }}"
        ansible_user: "{{ hostvars[item].ansible_user|default('root') }}"
        ansible_ssh_pass: "{{ hostvars[item].ansible_ssh_pass|default('') }}"
        ansible_become_user: root
        ansible_become_pass: "{{ hostvars[item].ansible_ssh_pass|default('') }}"
        groups: ambari-node
      with_items: "{{ groups['master-nodes']|sort|last }}"
      register: ambari-node 
      when: 
        - distro == "hdp"
        - "'ambari-node' not in groups or groups['ambari-node']|length < 1"

    - name: Add the last masternode to cm_node variable group
      check_mode: no
      add_host:
        name: "{{ hostvars[item].inventory_hostname }}"
        ansible_host: "{{ hostvars[item].ansible_host|default(hostvars[item].ansible_ssh_host) }}"
        ansible_user: "{{ hostvars[item].ansible_user|default('root') }}"
        ansible_ssh_pass: "{{ hostvars[item].ansible_ssh_pass|default('') }}"
        ansible_become_user: root
        ansible_become_pass: "{{ hostvars[item].ansible_ssh_pass|default('') }}"
        groups: cm_node
      with_items: "{{ groups['master-nodes']|sort|last }}"
      register: cm_node
      when:
        - distro == "cdh"
        - "'cm_node' not in groups or groups['cm_node']|length < 1"
      

