---
- include: create_groups.yml

- name: "Apply the ambari-agent role to all nodes"
  hosts: hadoop-cluster
  any_errors_fatal: true
  become: yes
  pre_tasks:
    - name: "Show hadoop-cluster info"
      debug: var=hostvars[inventory_hostname]
      when: debug
  roles:
    - ambari-agent
  tags:
    - ambari-agent-only

- name: "Apply the ambari-server role to ambari-node group"
  hosts: ambari-node
  become: yes
  roles:
    - ambari-server
  tags:
    - ambari-server-only
