---
- include: create_groups.yml

- name: "remove clouder-agent role to all nodes"
  hosts: hadoop-cluster
  any_errors_fatal: true
  become: yes
  pre_tasks:
    - name: "Show hadoop-cluster info"
      debug: var="{{ hostvars[inventory_hostname] }}"
      when: debug
  tasks:
    - name: "remove agent"
      yum: name='cloudera-manager-agent' state=removed

- name: "drop scm mysql mysql db on master nodes"
  hosts: cm_node
  any_errors_fatal: true
  become: yes
  pre_tasks:
    - name: "Show cluster info"
      debug: var="{{ hostvars[inventory_hostname] }}"
      when: debug
    - name: "include mysql vars"
      include_vars: roles/cloudera-mysql/vars/mysql_vars.yml
  tasks:
    - name: 'remove scm db from master nodes'
      mysql_db: name={{ item }} state=absent
      with_items:
        - db_names

- name: "remove cloudera-mngr role to cm-node group"
  hosts: cm_node
  become: yes
  pre_tasks:
    - name: "Show cluster info"
      debug: var="{{ hostvars[inventory_hostname] }}"
      when: debug
  tasks:
    - name: "remove cloudera manager"
      yum: name={{ item }} state=removed
      with_items:
        - cloudera-manager-server
        - cloudera-manager-daemons

- name: "cleanup dirs"
  hosts: hadoop_cluster
  become: yes
  tasks:
    - name: "remove dirs"
      file: path=/hadoop state=absent
