---
- include: create_groups.yml
  tags:
    - always

- name: "gather facts"
  hosts: hadoop-cluster
  gather_facts: true

- name: "generate site facts"
  hosts: localhost 
  any_errors_fatal: true
  become: no
  vars: 
    dnmemory: "{{ hostvars[groups['slave-nodes'][0]]['ansible_memtotal_mb'] / 1024 }}"
    mnmemory: "{{ hostvars[groups['master-nodes'][0]]['ansible_memtotal_mb'] / 1024 }}"
    cores: "{{ hostvars[groups['slave-nodes'][0]]['ansible_processor_count'] }}"
  tasks:
    - name: "run yarn utlils"
      action:
        module: sitefacts.py
          dnmemory="{{ dnmemory }}"
          mnmemory="{{ mnmemory }}"
          cores="{{ cores }}"

- name: "debug"
  hosts: localhost
  tasks:
#    - name: "debugging localhost var mapreduce_task_io_sort_mb" 
#      debug: var={{ hostvars['localhost']['mapreduce_task_io_sort_mb'] }}
    - name: "debug dict"
      debug: msg="this is a value {{ str(hostvars['localhost']['ams_hbase_env']['regionserver_xmn_size']) }}"
