---
- include: create_groups.yml
  tags:
    - always

- name: "gather facts"
  hosts: hadoop-cluster
  gather_facts: true

- name: "generate site facts"
  hosts: localhost 
  any_errors_fatal: true
  become: no
  vars: 
    dnmemory: "{{ hostvars[groups['slave-nodes'][0]]['ansible_memtotal_mb'] / 1024 }}"
    mnmemory: "{{ hostvars[groups['master-nodes'][0]]['ansible_memtotal_mb'] / 1024 }}"
    cores: "{{ hostvars[groups['slave-nodes'][0]]['ansible_processor_count'] }}"
  tasks:
    - name: "run yarn utlils"
      action:
        module: sitefacts.py
          dnmemory="{{ dnmemory }}"
          mnmemory="{{ mnmemory }}"
          cores="{{ cores }}"

- name: "debug"
  hosts: localhost
  tasks:
   -  debug: 
        msg:
         - "ams_env['metrics_collector_heapsize'] : {{ hostvars['localhost']['ams_env']['metrics_collector_heapsize'] }}"
         - "ams_hbase_env['hbase_master_heapsize'] : {{ hostvars['localhost']['ams_hbase_env']['hbase_master_heapsize'] }}"
         - "ams_hbase_env['hbase_master_xmn_size'] : {{ hostvars['localhost']['ams_hbase_env']['hbase_master_xmn_size'] }}"
         - "ams_hbase_env['hbase_regionserver_heapsize'] : {{ hostvars['localhost']['ams_hbase_env']['hbase_regionserver_heapsize'] }}"
         - "ams_hbase_env['regionserver_xmn_size'] : {{ hostvars['localhost']['ams_hbase_env']['regionserver_xmn_size'] }}"
         - "hadoop_env['dtnode_heapsize'] : {{ hostvars['localhost']['hadoop_env']['dtnode_heapsize'] }}"
         - "hadoop_env['namenode_heapsize'] : {{ hostvars['localhost']['hadoop_env']['namenode_heapsize'] }}"
         - "hadoop_env['namenode_opt_maxnewsize'] : {{ hostvars['localhost']['hadoop_env']['namenode_opt_maxnewsize']}}"
         - "hadoop_env['namenode_opt_newsize'] : {{ hostvars['localhost']['hadoop_env']['namenode_opt_newsize'] }}"
         - "hbase_env['hbase_master_heapsize'] : {{ hostvars['localhost']['hbase_env']['hbase_master_heapsize'] }}"
         - "hbase_env['hbase_regionserver_heapsize'] : {{ hostvars['localhost']['hbase_env']['hbase_regionserver_heapsize'] }}"
         - "hbase_env['hbase_regionserver_xmn_max'] : {{ hostvars['localhost']['hbase_env']['hbase_regionserver_xmn_max'] }}"
         - "hdfs_site['dfs_datanode_balance_bandwidthPerSec'] : {{ hostvars['localhost']['hdfs_site']['dfs_datanode_balance_bandwidthPerSec'] }}"
         - "hdfs_site['dfs_datanode_balance_trafnsfer_threads'] : {{ hostvars['localhost']['hdfs_site']['dfs_datanode_balance_trafnsfer_threads'] }}"
         - "hive_env['hive_client_heapsize'] : {{ hostvars['localhost']['hive_env']['hive_client_heapsize'] }}"
         - "hive_env['hive_heapsize'] : {{ hostvars['localhost']['hive_env']['hive_heapsize'] }}"
         - "hive_env['hive_metastore_heapsize'] : {{ hostvars['localhost']['hive_env']['hive_metastore_heapsize'] }}"
         - "hive_site['hive_tez_container_size'] : {{ hostvars['localhost']['hive_site']['hive_tez_container_size'] }}"
         - "mapred_site['mapreduce_map_java_opts'] : {{ hostvars['localhost']['mapred_site']['mapreduce_map_java_opts'] }}"
         - "mapred_site['mapreduce_map_memory_mb'] : {{ hostvars['localhost']['mapred_site']['mapreduce_map_memory_mb'] }}"
         - "mapred_site['mapreduce_reduce_java_opts'] : {{ hostvars['localhost']['mapred_site']['mapreduce_reduce_java_opts'] }}"
         - "mapred_site['mapreduce_reduce_memory_mb'] : {{ hostvars['localhost']['mapred_site']['mapreduce_reduce_memory_mb'] }}"
         - "mapred_site['mapreduce_task_io_sort_mb'] : {{ hostvars['localhost']['mapred_site']['mapreduce_task_io_sort_mb'] }}"
         - "mapred_site['yarn_app_mapreduce_am_command_opts'] : {{ hostvars['localhost']['mapred_site']['yarn_app_mapreduce_am_command_opts'] }}"
         - "mapred_site['yarn_app_mapreduce_am_resource_mb'] : {{ hostvars['localhost']['mapred_site']['yarn_app_mapreduce_am_resource_mb'] }}"
         - "spark_defaults['spark_driver_memory'] : {{ hostvars['localhost']['spark_defaults']['spark_driver_memory'] }}"
         - "spark_defaults['spark_yarn_am_memory'] : {{ hostvars['localhost']['spark_defaults']['spark_yarn_am_memory'] }}"
         - "spark_defaults['spark_yarn_am_memoryOverhead'] : {{ hostvars['localhost']['spark_defaults']['spark_yarn_am_memoryOverhead'] }}"
         - "spark_defaults['spark_yarn_driver_memoryOverhead'] : {{ hostvars['localhost']['spark_defaults']['spark_yarn_driver_memoryOverhead'] }}"
         - "spark_defaults['spark_yarn_executor_memoryOverhead'] : {{ hostvars['localhost']['spark_defaults']['spark_yarn_executor_memoryOverhead'] }}"
         - "spark_defaults['sparn_executor_memory'] : {{ hostvars['localhost']['spark_defaults']['spark_yarn_executor_memory'] }}"
         - "tez_site['tez_am_resource_memory_mb'] : {{ hostvars['localhost']['tez_site']['tez_am_resource_memory_mb'] }}"
         - "tez_site['tez_task_resource_memory_mb'] : {{ hostvars['localhost']['tez_site']['tez_task_resource_memory_mb'] }}"
         - "yarn_site['yarn_nodemanager_resource_memory_mb'] : {{ hostvars['localhost']['yarn_site']['yarn_nodemanager_resource_memory_mb'] }}"
         - "yarn_site['yarn_scheduler_maximum_allocation_mb'] : {{ hostvars['localhost']['yarn_site']['yarn_scheduler_maximum_allocation_mb'] }}"
         - "zeppelin_env['zeppelin_executor_memory'] : {{ hostvars['localhost']['zeppelin_env']['zeppelin_executor_memory'] }}"
      when: debug
