---
- include: create_groups.yml

- name: "install sensu client"
  hosts: hadoop-cluster
  any_errors_fatal: true
  become: yes
  pre_tasks:
    - name: "Show hadoop-cluster info"
      debug: var=hostvars[inventory_hostname]
      when: debug
  roles:
    - monitoring/sensu

- name: "Apply the ambari-server role to ambari-node group"
  hosts: ambari-node
  become: yes
  roles:
    - monitoring/sensu/ambari
