---
- name: Load OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family|lower }}.yml"
        - defaults.yml
      paths:
        - ../vars

- name: Install the Ambari server
  action: "{{ package_info.pkg_mgr }}"
  args: package_info.args
  with_items: package_info.pkgs
  when: package_info.pkgs|length > 0

- include: spark_stack.yml
  when: spark_stack and ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

- name: Run Ambari Server setup
  shell: /usr/sbin/ambari-server setup -s

- name: because packaging is hard
  copy: src=ambari-server.service  dest=/usr/lib/systemd/system/ambari-server.service

- name: Enable the ambari-server service
  service: name=ambari-server state=started enabled=yes

- name: Waiting for ambari-server to start listening on port 8080
  wait_for: host={{ansible_fqdn}} port=8080

- name: Waiting for ambari-agents to register
  uri: url=http://{{ ansible_fqdn }}:8080/api/v1/hosts/{{ hostvars[item]['ansible_fqdn'] | lower }}
       method=GET
       force_basic_auth=yes
       user=admin
       password=admin
       HEADER_X-Requested-By="ambari"
       status_code=200,201,202,404
  with_items: groups['hadoop-cluster']
  register: result
  until: "result.status != 404"
  retries: 200
  delay: 5
